# Generated by Django 4.2.1 on 2023-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_auto_20230516_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
