# Generated by Django 4.2 on 2023-05-15 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="user_id",
            new_name="user_chatbot",
        ),
    ]
